name: find_a_dental_clinic

description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # For permission
  permission_handler: ^10.4.3

  # Goggle map
  google_maps_flutter: ^2.3.1

dev_dependencies:

  flutter_test:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # To draw poly lines in map
  flutter_polyline_points: ^1.0.0

  # Geocoding for position
  geocoding: ^2.1.0

  # Request for location
  geolocator: ^9.0.2


  # Firebase firestore
  cloud_firestore: ^4.8.1

  # For REST API consumption
  http: ^0.13.1

  # Google fonts
  google_fonts: ^4.0.4


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/



























