// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaqwKWZrGw78jc91XPsAwRxjxmeX8hWpo',
    appId: '1:541149552427:web:3bfd1b50b9bc714565ef6e',
    messagingSenderId: '541149552427',
    projectId: 'find-a-dental-clinic',
    authDomain: 'find-a-dental-clinic.firebaseapp.com',
    storageBucket: 'find-a-dental-clinic.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ODX40Jlg4oQaK6hzpXOUTuNIZ036TW0',
    appId: '1:541149552427:android:f174cb5a2ecc2da065ef6e',
    messagingSenderId: '541149552427',
    projectId: 'find-a-dental-clinic',
    storageBucket: 'find-a-dental-clinic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjN_-znXup6bbxt02LJ1aFKhpRLLxBpGA',
    appId: '1:541149552427:ios:de32b93139de0f4265ef6e',
    messagingSenderId: '541149552427',
    projectId: 'find-a-dental-clinic',
    storageBucket: 'find-a-dental-clinic.appspot.com',
    iosClientId: '541149552427-lti4futev1lj91nik1un3jej7iv3sc8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.findADentalClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjN_-znXup6bbxt02LJ1aFKhpRLLxBpGA',
    appId: '1:541149552427:ios:e0f80ceae0bef79365ef6e',
    messagingSenderId: '541149552427',
    projectId: 'find-a-dental-clinic',
    storageBucket: 'find-a-dental-clinic.appspot.com',
    iosClientId: '541149552427-hdea3t3ag2ann37b1sn3af91p5j772co.apps.googleusercontent.com',
    iosBundleId: 'com.example.findADentalClinic.RunnerTests',
  );
}
